// ─── Main Platform Disclaimer ─────────────────────────────────────────────────

export const MAIN_DISCLAIMER = `Lexora provides AI-assisted arbitration as a non-binding, voluntary dispute resolution service.
Outcomes produced by Lexora are not legally enforceable judgments and do not constitute legal advice.
By using this platform, you agree that Lexora rulings are advisory in nature and that neither party
waives any legal rights by participating. Lexora is not a law firm, arbitral institution, or regulated
dispute resolution body. For legally binding arbitration, consult a qualified legal professional or
recognised arbitral body in your jurisdiction.`;

// ─── Ruling Disclaimer ────────────────────────────────────────────────────────

export const RULING_DISCLAIMER = `This ruling was generated by an AI system trained on general dispute resolution principles
and the framework selected for this case. It is not a legal judgment. The ruling reflects a
reasonable assessment of the evidence presented and is intended to assist parties in reaching
a fair resolution. Parties are under no obligation to comply, but acceptance of the ruling
constitutes a voluntary agreement between the parties.`;

// ─── High Risk Disclaimer ─────────────────────────────────────────────────────

export const HIGH_RISK_DISCLAIMER = `This dispute involves claims or circumstances that may have significant financial or legal
consequences. Lexora strongly recommends consulting a qualified lawyer before submitting,
accepting, or acting on any ruling in cases involving large sums, regulatory matters,
intellectual property rights, or potential criminal conduct. Lexora accepts no liability
for outcomes arising from reliance on its rulings.`;

// ─── Out-of-scope Categories ──────────────────────────────────────────────────

export const OUT_OF_SCOPE_CATEGORIES: string[] = [
  "Criminal matters or allegations of fraud",
  "Family law, divorce, or child custody disputes",
  "Real estate or land title disputes",
  "Employment termination and labour law claims",
  "Personal injury or medical negligence",
  "Insolvency, bankruptcy, or winding-up proceedings",
  "Regulatory enforcement or government actions",
  "Tax disputes or financial reporting matters",
  "Class actions or multi-party litigation",
  "Constitutional or human rights claims",
  "Disputes involving minors",
  "Matters currently before a court or tribunal",
];

// ─── Framework-Specific Notices ───────────────────────────────────────────────

export const WEB3_DISCLAIMER = `On-chain transactions are irreversible. Lexora rulings related to smart contract
escrow or token transfers can only be enforced if both parties agree to act on the
ruling. Lexora has no ability to directly interact with or reverse blockchain transactions.`;

export const IP_DISCLAIMER = `Intellectual property rights are complex and jurisdiction-dependent. Lexora's
rulings on content licensing disputes are based on the license terms presented
and general principles. They do not constitute a legal finding of copyright
infringement or grant, modify, or extinguish any intellectual property rights.`;
