import type { ArbitrationFramework } from "@/lib/genlayer/types";

export const FRAMEWORKS: ArbitrationFramework[] = [
  {
    frameworkId: "freelance_milestone_delivery",
    title: "Freelance Milestone Delivery",
    category: "Freelance & Services",
    description:
      "Resolves disputes between freelancers and clients where work was commissioned in clearly defined milestones. Covers non-delivery, partial delivery, quality disputes, and scope disagreements on digital work.",
    principles: [
      "Work must meet the specifications agreed at the time of contract",
      "Milestones are evaluated against the original brief, not evolving expectations",
      "Payment is owed for accepted or substantially complete work",
      "Revisions within scope are a contractual obligation, not optional",
      "Late delivery is a breach unless force majeure or client-caused delay applies",
    ],
    decisionFactors: [
      "Clarity of the original milestone specification",
      "Whether deliverables were submitted on time",
      "Degree of completeness vs stated requirements",
      "Client responsiveness and feedback during delivery",
      "Evidence of revision requests and responses",
      "Payment history and agreed schedule",
    ],
    remedyOptions: [
      "Full payment release for completed milestones",
      "Partial payment proportional to work delivered",
      "Refund of advance payment for undelivered work",
      "Rework order with defined timeline",
      "Contract cancellation with settled accounting",
    ],
    burdenOfProof: "BALANCED",
    evidenceRules: [
      "Original project brief or scope document is primary evidence",
      "Submitted deliverables must be demonstrably linked to milestone requirements",
      "Client feedback and revision requests must be documented",
      "Communications via agreed channel (email/platform) carry full weight",
      "Verbal agreements require corroborating evidence to be considered",
    ],
    excludedMatters: [
      "Physical product manufacturing disputes",
      "Employment relationship claims",
      "IP ownership disputes beyond what is specified in contract",
      "Claims for consequential damages or lost profits",
    ],
    icon: "💼",
  },
  {
    frameworkId: "digital_service_refund",
    title: "Digital Service Refund",
    category: "Consumer & Subscriptions",
    description:
      "Handles refund disputes for digital services, SaaS subscriptions, online courses, and software licenses where the service was materially different from what was advertised or was inaccessible.",
    principles: [
      "Services must match the description and advertised capabilities",
      "Inaccessibility due to provider fault entitles the user to a pro-rated refund",
      "Refund windows stated at purchase are binding on both parties",
      "Partial use of a service does not automatically forfeit refund rights",
      "Provider must demonstrate the service was reasonably available",
    ],
    decisionFactors: [
      "Advertised vs actual service capabilities",
      "Duration and frequency of service downtime or unavailability",
      "Whether the user was notified of material changes",
      "Time elapsed since purchase and extent of service use",
      "Stated refund policy at time of purchase",
      "Evidence of user attempts to resolve with provider",
    ],
    remedyOptions: [
      "Full refund within refund window",
      "Pro-rated refund for unused subscription period",
      "Service credit for equivalent value",
      "Partial refund reflecting service actually received",
      "No refund where service substantially performed as described",
    ],
    burdenOfProof: "RESPONDENT",
    evidenceRules: [
      "Screenshot of advertised features at time of purchase is primary evidence",
      "Service uptime logs and provider acknowledgments are authoritative",
      "User must document attempts to contact support before disputing",
      "Refund policy must be the version presented at point of purchase",
      "Chargebacks or prior disputes reduce credibility of new claim",
    ],
    excludedMatters: [
      "Physical goods and shipping disputes",
      "Disputes about subjective content quality (e.g., course teaching style)",
      "Claims based on change of mind alone",
      "Disputes exceeding 12 months from purchase date",
    ],
    icon: "📄",
  },
  {
    frameworkId: "marketplace_order_dispute",
    title: "Marketplace Order Dispute",
    category: "E-Commerce & Marketplace",
    description:
      "Resolves disputes between buyers and sellers on peer-to-peer or managed marketplaces, covering non-delivery, item not as described, counterfeit goods, and unauthorized transactions.",
    principles: [
      "Sellers must deliver items that match the listing description",
      "Delivery is the seller's responsibility until buyer confirms receipt",
      "Photographs and listing content form part of the contractual description",
      "Buyers must raise disputes within a reasonable window post-delivery",
      "Platform escrow or payment timing rules are incorporated by reference",
    ],
    decisionFactors: [
      "Match between listing description and delivered item",
      "Tracking and delivery confirmation evidence",
      "Timing of dispute relative to delivery or expected delivery",
      "Communication between buyer and seller prior to escalation",
      "Platform rules applicable at time of transaction",
      "Photos or inspection reports of received item",
    ],
    remedyOptions: [
      "Full refund with return of item",
      "Partial refund for item discrepancy",
      "Replacement item from seller",
      "Release of funds to seller on confirmed delivery",
      "Cancellation and full refund for non-delivery",
    ],
    burdenOfProof: "BALANCED",
    evidenceRules: [
      "Original listing screenshot or archived page is primary evidence",
      "Shipping tracking must be from a verifiable courier",
      "Photos of received item must be timestamped or independently verifiable",
      "Platform transaction records take precedence over private communications",
      "Third-party authentication reports accepted for counterfeit claims",
    ],
    excludedMatters: [
      "B2B wholesale disputes",
      "Disputes involving regulated goods (pharmaceuticals, weapons, etc.)",
      "Claims for consequential or indirect losses",
      "Disputes based solely on buyer's change of preference",
    ],
    icon: "🛒",
  },
  {
    frameworkId: "private_agreement_breach",
    title: "Private Agreement Breach",
    category: "Private Contracts",
    description:
      "Adjudicates breaches of private agreements between individuals or entities where no specialized framework applies. Covers failure to perform, payment defaults, and material misrepresentation.",
    principles: [
      "A valid agreement requires offer, acceptance, and consideration",
      "Parties must perform their obligations in good faith",
      "Material breach entitles the non-breaching party to remedies",
      "Written terms take precedence over oral representations",
      "Course of dealing and conduct can clarify ambiguous terms",
    ],
    decisionFactors: [
      "Existence and validity of the agreement",
      "Clarity of obligations on each party",
      "Evidence of breach or non-performance",
      "Whether breach was material or minor",
      "Steps taken to cure or mitigate the breach",
      "Damages that are directly caused by the breach",
    ],
    remedyOptions: [
      "Specific performance order",
      "Monetary compensation for direct losses",
      "Rescission of the agreement",
      "Partial performance payment",
      "Declaratory finding of breach with no damages",
    ],
    burdenOfProof: "CLAIMANT",
    evidenceRules: [
      "Written agreement signed by both parties is strongest evidence",
      "Email or message chains confirming terms are admissible",
      "Party asserting breach must demonstrate obligation and non-performance",
      "Quantum of damages must be supported by documentary evidence",
      "Hearsay evidence given low weight without corroboration",
    ],
    excludedMatters: [
      "Consumer-to-business disputes (use appropriate sector framework)",
      "Employment contract disputes",
      "Real property transactions",
      "Family law matters",
    ],
    icon: "📜",
  },
  {
    frameworkId: "dao_grant_performance",
    title: "DAO Grant Performance",
    category: "Web3 & DAO",
    description:
      "Resolves disputes between DAOs or protocol treasuries and grant recipients where deliverables were not met, funds were misused, or milestones were not reached by agreed dates.",
    principles: [
      "Grant recipients must deliver on the approved proposal milestones",
      "DAO governance decisions on grant terms are binding",
      "Public commitments made in proposal are incorporated as obligations",
      "Milestone extensions require explicit DAO or committee approval",
      "Funds must be used for the approved purposes stated in the proposal",
    ],
    decisionFactors: [
      "Approved proposal and milestone specifications",
      "Actual deliverables submitted against milestones",
      "Governance votes approving or modifying grant terms",
      "On-chain fund movements and wallet activity",
      "Committee communications and status updates provided",
      "Timeline adherence and extension requests",
    ],
    remedyOptions: [
      "Clawback of unspent or misused funds",
      "Milestone payment release for completed work",
      "Grant cancellation with partial refund",
      "Revised milestone schedule with retained funding",
      "Public finding with no financial remedy",
    ],
    burdenOfProof: "CLAIMANT",
    evidenceRules: [
      "Approved governance proposal is the primary contract document",
      "On-chain transactions are authoritative for fund movements",
      "Forum posts and snapshot votes are admissible as governance evidence",
      "GitHub commits and product deployments serve as delivery evidence",
      "Committee meeting notes must be corroborated by on-chain records",
    ],
    excludedMatters: [
      "Disputes about DAO governance legitimacy itself",
      "Token price or investment performance claims",
      "Disputes involving illegal activities",
      "Claims against DAO smart contracts for bugs or exploits",
    ],
    icon: "🏛️",
  },
  {
    frameworkId: "small_contractor_completion",
    title: "Small Contractor Completion",
    category: "Trades & Construction",
    description:
      "Handles disputes between clients and small contractors or tradespeople over completion quality, timeline breaches, and payment for physical or digital construction and installation work.",
    principles: [
      "Contractors must complete work to the standard specified or implied by trade norms",
      "Clients must provide access, materials (where agreed), and timely payment",
      "Substantial completion triggers payment even if minor defects remain",
      "Defects discovered after completion entitle clients to remediation, not automatic refund",
      "Change orders must be agreed in writing to be enforceable",
    ],
    decisionFactors: [
      "Scope of work as agreed in the contract or quote",
      "Evidence of completion or partial completion",
      "Nature and severity of defects or incomplete work",
      "Whether client accepted or used the completed work",
      "Payment history and retainage terms",
      "Third-party inspection or expert assessment",
    ],
    remedyOptions: [
      "Release of final payment on substantial completion",
      "Retention of payment pending remediation",
      "Partial payment with agreed defect schedule",
      "Rework order with cost allocation",
      "Refund of deposit for abandonment of work",
    ],
    burdenOfProof: "BALANCED",
    evidenceRules: [
      "Signed quote or contract is the primary scope document",
      "Photographs of work in progress and completion are required",
      "Third-party inspection reports carry high weight",
      "Client sign-off, even informal, indicates acceptance",
      "Change orders without written agreement are inadmissible",
    ],
    excludedMatters: [
      "Large-scale commercial construction projects",
      "Regulatory compliance or building code violations",
      "Personal injury claims arising from work",
      "Disputes involving licensed professional certifications",
    ],
    icon: "🔧",
  },
  {
    frameworkId: "content_licensing_dispute",
    title: "Content Licensing Dispute",
    category: "Intellectual Property",
    description:
      "Resolves disputes over the use of licensed content â€” images, music, video, written works, code, and AI-generated assets â€” including unauthorized use, license scope violations, and attribution failures.",
    principles: [
      "Use of content must fall within the scope of the granted license",
      "Attribution requirements are contractual obligations, not optional",
      "A license grants only the rights explicitly stated; all others are reserved",
      "Unlicensed use is a breach regardless of commercial intent",
      "Fair use claims require context-specific assessment and are fact-dependent",
    ],
    decisionFactors: [
      "Terms of the license at time of use",
      "Scope of actual use vs permitted use",
      "Attribution provided vs required",
      "Whether use was commercial or non-commercial",
      "Platform or distribution channel of the content",
      "Evidence of unauthorized modification or sublicensing",
    ],
    remedyOptions: [
      "Licensing fee payment for unauthorized use",
      "Take-down order for infringing content",
      "License fee refund for scope overpayment",
      "Attribution correction requirement",
      "Declaratory finding of license compliance",
    ],
    burdenOfProof: "CLAIMANT",
    evidenceRules: [
      "Original license agreement or Creative Commons designation is primary evidence",
      "Screenshots or archive links of infringing use must be time-stamped",
      "Platform metadata (publish date, modification history) is admissible",
      "Expert opinion on fair use grounds is weighted but not determinative",
      "Licensing platform records (Getty, Shutterstock, etc.) are authoritative",
    ],
    excludedMatters: [
      "Copyright registration or validity challenges",
      "Criminal IP infringement",
      "Trademark disputes",
      "Disputes involving open source license compatibility (GPL, AGPL, etc.)",
    ],
    icon: "©️",
  },
];

